apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
    jenkins/label-digest: "03ddc3eddf95d5470d5c7fb6d2937abaeca3b79e"
    jenkins/label: ubuntu-agent
  name: ubuntu-agent
  namespace: tools
spec:
  serviceAccountName: jenkins
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
      readOnly: false
    - mountPath: /root/.kube
      name: kubeconfig
      readOnly: true
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: kubeconfig
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 86400
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock