
- name: Install docker prerquests
  apt:
    pkg:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Update keyrings permissions
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  block:
    - name: docker repo | no apt key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
    - name: docker repo | apt source
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: "docker"
        state: present

- name: Update permissions to docker.asc
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: {{ ansible_user_id }}
    groups: docker
    append: yes

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes