- include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- include_tasks: centos.yml
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"