apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: localhost:30004/repository/docker-repo/nodejs-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: mysql-secret