- name: Install minikube package
  apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    state: present

- name: Start the cluster
  command: su - "{{ current_user.stdout }}" -c "minikube start"